### ISSUE TITLE
`<kami-text-editor>`

### ISSUE THREAD

**Issue by EmilienLeroy** [Kamiapp-fr/kami-collection#34]
# TODO

- [ ] Simple html text editor
- [ ] Support external file like video, img, pdf, etc
- [ ] Mention system using `@` or a custom tag
