### ISSUE TITLE
`<kami-changelog>`

### ISSUE THREAD

**Issue by EmilienLeroy** [Kamiapp-fr/kami-collection#36]
# TODO

- [x] Parse changelog to create a beautiful notification component on new release
- [x] Support github release
- [x] Support gitlab release
